jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: 
        - name: Test pipe
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python test.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
